# inherit_from: .rubocop_todo.yml
AllCops:
  NewCops: enable
  Exclude:
   - "bin/*"
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Style/Documentation:
  Enabled: false
